#!pip install transformers==4.41.1
#!pip install pyyaml
#!pip install torchvision==0.18.1
#!pip install torch==2.3.1
#!pip install pillow==9.5.0
#!pip install --extra-index-url https://miropsota.github.io/torch_packages_builder detectron2==0.6+pt2.3.0cu121

EXECUTOR: "ExExecutor"
## Training param
DEVICE: "cuda"

SAVE: TRUE
SAVE_PATH: "ReceiptVQA_exp/models/"

LR: 0.00005
BETAS: 
  - 0.9
  - 0.98

warmup_step: 5000

NUM_EPOCHS: 10
TRAIN_BATCH_SIZE: 8
EVAL_BATCH_SIZE: 16
PREDICT_BATCH_SIZE: 16

STEP_MODE: FALSE
END_STEP: 50000
show_loss_after_steps: 200
eval_after_steps: 2000


get_predict_score: TRUE

##DATA
ocr_path: "./google_ocr"
max_length: 180

root_feature_path: ./xlm_img/

qa_train_path: "./ReceiptVQA/ReceiptVQA_train.csv"
qa_val_path: "./ReceiptVQA/ReceiptVQA_dev.csv"
qa_predict_path:  "./ReceiptVQA/ReceiptVQA_dev.csv"

DATASET_CLASS: "LayoutXLMVQADataset"

## MODEL
isLiLT: FALSE

model_name: "microsoft/layoutxlm-base"